// flow-typed signature: 0b59a3bae9d0faefc98d1c5360d21dfc
// flow-typed version: <<STUB>>/apollo-tools_v0.0.20/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-tools/lib/apollo' {
  declare module.exports: any;
}

declare module 'apollo-tools/lib/configure-client' {
  declare module.exports: any;
}

declare module 'apollo-tools/lib/configure-server' {
  declare module.exports: any;
}

declare module 'apollo-tools/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-tools/index' {
  declare module.exports: $Exports<'apollo-tools'>;
}
declare module 'apollo-tools/index.js' {
  declare module.exports: $Exports<'apollo-tools'>;
}
declare module 'apollo-tools/lib/apollo.js' {
  declare module.exports: $Exports<'apollo-tools/lib/apollo'>;
}
declare module 'apollo-tools/lib/configure-client.js' {
  declare module.exports: $Exports<'apollo-tools/lib/configure-client'>;
}
declare module 'apollo-tools/lib/configure-server.js' {
  declare module.exports: $Exports<'apollo-tools/lib/configure-server'>;
}
declare module 'apollo-tools/lib/index.js' {
  declare module.exports: $Exports<'apollo-tools/lib/index'>;
}
